# Generated by Django 4.2.4 on 2023-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(blank=True, max_length=100)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('softwareusername', models.TextField(max_length=255)),
                ('expirationdate', models.DateField(verbose_name='%m/%d/%Y')),
                ('version', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
                ('updated_at', models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S')),
            ],
        ),
    ]
